server:
  port: 8088

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: test1
          uri: http://localhost:8001
          predicates:
            - Path=/test1/**
        - id: test2
          uri: http://localhost:8002
          predicates:
            - Path=/test2/**